# config/routes.yaml

# 1.  importujemy trasy API.
#    Symfony sprawdzi je jako pierwsze.
api:
    resource: 'routes/api_routes.yaml'

# 2.  importujemy trasę "catch-all".
#    Zostanie sprawdzona tylko, jeśli żadna trasa API nie pasowała.
frontend:
    resource: 'routes/frontend_routes.yaml'